name: CI

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release] 
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code     
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.0.2    
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
      - name: Restore NuGet Packages
        run: nuget restore TicketManagement.sln 
      - name: Setup VSTest.exe
        uses: Malcolmnixon/Setup-VSTest@v3	
      - name: Setup SqlPackage
        uses: coreywebber/setup-sqlpackage@v1.0.0  
      - name: Build
        run: msbuild TicketManagement.sln /p:Configuration=${{ matrix.configuration }} 
      - name: Unit tests
        run: vstest.console **\*.UnitTests.dll 
      - name: Database publish
        run: sqlpackage.exe /Action:Publish /TargetDatabaseName:"TicketManagement.Database" /TargetServerName:"localhost\SQLEXPRESS" /SourceFile:".\src\TicketManagement.Database\bin\${{ matrix.configuration }}\TicketManagement.Database.dacpac"  /p:CreateNewDatabase="true"  
      - name: Integration tests
        run: vstest.console **\*.IntegrationTests.dll  
    
    